/// Data Fetcher Service - Scientific Version
/// Protocol: Antigravity - Mobile Module
///
/// This service handles loading stock data from local files.
/// Direct API calls are STRRICTLY PROHIBITED to maintain integrity.
/// Data must be imported from the Flet/tvdatafeed module.

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

class DataFetcher {
  final String _cacheDir;

  DataFetcher(this._cacheDir);

  /// Fetch latest data for a symbol from local storage.
  /// This expects a JSON file generated by the tvdatafeed module.
  Future<Map<String, dynamic>?> fetchLatestData(String symbol) async {
    try {
      final file = File('$_cacheDir/data_cache/$symbol.json');
      
      if (await file.exists()) {
        final content = await file.readAsString();
        final data = jsonDecode(content);
        
        return {
          'symbol': symbol,
          'features': (data['features'] as List).cast<double>(),
          'lastClose': (data['ohlcv']?['close'] as num?)?.toDouble() ?? 0.0,
          'timestamp': data['timestamp'],
          'isLive': true,
        };
      }
      return null;
    } catch (e) {
      print('❌ Error loading data for $symbol: $e');
      return null;
    }
  }

  /// Saves imported data JSON to local storage
  Future<void> importDataJson(String symbol, String jsonContent) async {
    final dir = Directory('$_cacheDir/data_cache');
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    final file = File('${dir.path}/$symbol.json');
    await file.writeAsString(jsonContent);
    print('✅ Imported data for $symbol');
  }
  
  /// Helper for square root (since we removed dart:math for some reason in previous version)
  double customSqrt(double x) {
    if (x <= 0) return 0;
    return pow(x, 0.5).toDouble();
  }
}
